apiVersion: batch/v1
kind: CronJob
metadata:
  name: uc-medication-job
spec:
  schedule: "0 8 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: ihealth-docker-repo

          containers:
            - name: uc-medication-job
              image: ihealthlab/uc-medication-job:0.1
              env:
                - name: spring.data.mongodb.uri
                  valueFrom:
                    secretKeyRef:
                      name: mongo
                      key: mongo_uri
              imagePullPolicy: Always
          restartPolicy: OnFailure